#!/bin/bash
net_mgmt_name=$1
net_vsg_name=$2
instance_name=$3
echo "Create instance with net-mgmt $net_mgmt_name , net-vsg $net_vsg_name , instance-name $instance_name"

source $HOME/admin-openrc.sh
openstack port create --network management $1
openstack port create --network mysite_vsg-access $2


id_net_mgmt=$(openstack port list | grep $net_mgmt_name | awk '{print $2}')
id_net_vsg=$(openstack port list | grep $net_vsg_name | awk '{print $2}')

#echo $id_net_mgmt
#echo $id_net_vsg
nova boot --image hack-ubuntu --flavor 2 --nic port-id=$id_net_mgmt --nic port-id=$id_net_vsg $instance_name
id_instance=$(openstack server list --all-projects | grep $instance_name | awk '{print $2}')
echo "create instance with ID:$id_instance"

#echo "for"
#for i in "$@"
#do
#  echo $i
#  shift
#done
